---
abstract: 'Autoboxed wrappers for Native Perl datatypes '
author:
  - 'Stevan Little <stevan@iinteractive.com>'
build_requires:
  ExtUtils::MakeMaker: 0
  Test::Exception: 0.21
  Test::More: 0.89
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.8, CPAN::Meta::Converter version 2.132830'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Moose-Autobox
no_index:
  directory:
    - t
    - inc
requires:
  Moose: 0.42
  Syntax::Keyword::Junction: 0
  autobox: 2.23
  parent: 0
resources:
  repository: https://github.com/moose/Moose-Autobox.git
version: 0.15
x_bugtracker:
  web: https://github.com/moose/Moose-Autobox/issues
