---
abstract: 'Autoboxed wrappers for Native Perl datatypes '
author:
  - 'Stevan Little <stevan@iinteractive.com>'
build_requires:
  Test::Exception: 0.21
  Test::More: 0.62
distribution_type: module
generated_by: 'Module::Install version 0.77'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Moose-Autobox
no_index:
  directory:
    - inc
    - t
    - examples
requires:
  Moose: 0.42
  Perl6::Junction: 1.40000
  autobox: 2.23
  perl: 5.6.0
resources:
  license: http://dev.perl.org/licenses/
version: 0.09
